services:
  bookingdb:
    image: mysql:8.0
    container_name: bookingdb
    healthcheck:
      test: ["CMD-SHELL","mysqladmin" , "ping","-h","bookingdb"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD : bookings
      MYSQL_DATABASE : bookings

  paymentdb:
    image: mysql:8.0
    container_name: paymentdb
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","paymentdb"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: payments
      MYSQL_DATABASE: payments
    ports:
      - "3308:3306"

  booking-service:
    image: booking-service
    container_name: booking-service
    build: ./booking-service
    depends_on:
      bookingdb:
        condition: service_healthy
    ports:
      - "9090:9090"
    environment:
      MYSQL_HOST: bookingdb
      DB_NAME: bookings
  payment-service:
    image: payment-service
    container_name: payment-service
    build: ./payment-service
    depends_on:
      paymentdb:
        condition: service_healthy
    ports:
      - "9091:9091"